services:
  backend:
    build: .
    container_name: laborit-backend
    ports:
      - 3333:3333
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3333"]
      interval: 30s
      timeout: 10s
      retries: 5
